### ISSUE TITLE
Instant Processing of text file 'HacKingdom'.

### ISSUE THREAD

**Issue by GayKiwi** [hackerwars-io/issue-tracker#54] opened 2019-11-11 11:20 UTC
While uploading the text file "HacKingdom" to the clan server "HacKingdom" during round 3, the process showed a white page, uploaded the file instantly, created no logs on either the Clan or my localhost.

**Comment by Ni3zam** [comment] 2019-11-11 13:48
Hello, can you provide screenshot or other kind of proof? I would like to see it😊

**Comment by hackerwars** [comment] 2021-02-06 05:57
Unable to reproduce or look into why this happened - closing for now. Thanks for reporting.

**Closed by hackerwars** 2021-02-06 05:57 UTC
